### ISSUE TITLE
Lock Violation

### ISSUE THREAD

**Issue by cactushydrocodone** [PermaNulled/xg-sickbeard#4]
Hi i found a bug as i was building the solution on mono.
The building worked, but i cant execute it.

Error Stack:

> `04-09-2016 12:18:58,950 FATAL [ 1] 0:XG.Plugin.AWorker.Start()
> Db4objects.Db4o.Ext.DatabaseFileLockedException: /home/administrator/.config/XG/xgobjects.db4o ---> System.IO.IOException: Lock violation on path /home/administrator/.config/XG/xgobjects.db4o
>   at System.IO.FileStream.Lock (Int64 position, Int64 length) <0x7f92e2507ed0 + 0x00108> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.Platform4.LockFile (System.String path, System.Object file) <0x40c69fa0 + 0x00061> in <filename unknown>:0
>   --- End of inner exception stack trace ---
>   at Db4objects.Db4o.Internal.Platform4.LockFile (System.String path, System.Object file) <0x40c69fa0 + 0x000b7> in <filename unknown>:0
>   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile (System.String path, Boolean readOnly, Boolean lockFile) <0x40c69c90 + 0x0008f> in <filename unknown>:0
>   at Db4objects.Db4o.IO.FileStorage+FileBin..ctor (Db4objects.Db4o.IO.BinConfiguration config) <0x40c69980 + 0x0011f> in <filename unknown>:0
>   at Db4objects.Db4o.IO.FileStorage.Open (Db4objects.Db4o.IO.BinConfiguration config) <0x40c69930 + 0x00033> in <filename unknown>:0
>   at Db4objects.Db4o.IO.StorageDecorator.Open (Db4objects.Db4o.IO.BinConfiguration config) <0x40c698e0 + 0x00028> in <filename unknown>:0
>   at Db4objects.Db4o.IO.CachingStorage.Open (Db4objects.Db4o.IO.BinConfiguration config) <0x40c69750 + 0x0001f> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl () <0x40c68de0 + 0x002d8> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.ObjectContainerBase+_IRunnable_129.Run () <0x40c60950 + 0x00173> in <filename unknown>:0
>   at Db4objects.Db4o.Foundation.DynamicVariable.With (System.Object value, IRunnable block) <0x40c606f0 + 0x0005e> in <filename unknown>:0
>   at Db4objects.Db4o.Foundation.Environments.RunWith (IEnvironment environment, IRunnable runnable) <0x40c606c0 + 0x00026> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment (IRunnable runnable) <0x40c60680 + 0x00023> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.ObjectContainerBase.Open () <0x40c60600 + 0x00063> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor (IConfiguration config, System.String fileName) <0x40c5f2a0 + 0x00103> in <filename unknown>:0
>   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer (IEmbeddedConfiguration config, System.String databaseFileName) <0x40c5ef40 + 0x0005f> in <filename unknown>:0
>   at Db4objects.Db4o.Db4oEmbedded.OpenFile (IEmbeddedConfiguration config, System.String databaseFileName) <0x40c5ee30 + 0x00023> in <filename unknown>:0
>   at XG.DB.Dao.StartRun () <0x40c52670 + 0x001ab> in <filename unknown>:0
>   at XG.Plugin.AWorker.Start (System.String aName, Boolean aNewThread) <0x40c524d0 + 0x00109> in <filename unknown>:0
> 
> Unhandled Exception:
> System.NullReferenceException: Object reference not set to an instance of an object
>   at XG.Business.Helper.Objects.CheckAndRemoveDuplicates (XG.Model.Domain.Servers aServers) <0x40c7aa80 + 0x0004e> in <filename unknown>:0
>   at XG.Business.App..ctor () <0x40c35840 + 0x002c7> in <filename unknown>:0
>   at XG.Application.Programm.Main (System.String[] args) <0x40bd3670 + 0x00acf> in <filename unknown>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at XG.Business.Helper.Objects.CheckAndRemoveDuplicates (XG.Model.Domain.Servers aServers) <0x40c7aa80 + 0x0004e> in <filename unknown>:0
>   at XG.Business.App..ctor () <0x40c35840 + 0x002c7> in <filename unknown>:0
>   at XG.Application.Programm.Main (System.String[] args) <0x40bd3670 + 0x00acf> in <filename unknown>:0`

**Comment by cactushydrocodone** [comment]
SOLUTION FOR THIS:

RENAME /home/username/.config/XG/xgobjects.db4o to something another and start it again, it will recreate the file and works like expected!

**Comment by pnill** [comment]
Yeah it looks as if the DB was either in a locked state, or had incorrect permissions... glad you were able to figure it out.
